// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {girc} from '../models';
import {config} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function GetServerChannel(arg1:string,arg2:string):Promise<girc.Channel>;

export function GetServerChannels(arg1:string):Promise<Array<girc.Channel>>;

export function GetServerConfig(arg1:string):Promise<config.ConfigServer>;

export function GetServerEvents(arg1:string):Promise<Array<girc.Event>>;

export function GetServersIDs():Promise<Array<string>>;

export function GetUsersForChannel(arg1:string,arg2:string):Promise<Array<girc.User>>;

export function Run(arg1:context.Context):Promise<void>;
