// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['servermanager']['ServerManager']['Close']();
}

export function GetServerChannel(arg1, arg2) {
  return window['go']['servermanager']['ServerManager']['GetServerChannel'](arg1, arg2);
}

export function GetServerChannels(arg1) {
  return window['go']['servermanager']['ServerManager']['GetServerChannels'](arg1);
}

export function GetServerConfig(arg1) {
  return window['go']['servermanager']['ServerManager']['GetServerConfig'](arg1);
}

export function GetServerEvents(arg1) {
  return window['go']['servermanager']['ServerManager']['GetServerEvents'](arg1);
}

export function GetServersIDs() {
  return window['go']['servermanager']['ServerManager']['GetServersIDs']();
}

export function GetUsersForChannel(arg1, arg2) {
  return window['go']['servermanager']['ServerManager']['GetUsersForChannel'](arg1, arg2);
}

export function Run(arg1) {
  return window['go']['servermanager']['ServerManager']['Run'](arg1);
}
